name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest
    outputs:
      dmg-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv venv .venv
      - run: |
          source .venv/bin/activate
          uv sync
          pyinstaller app.py \
            --name=MyTool \
            --windowed \
            --icon=favo.icns \
            --add-data "favo.png:." \
            --add-data ".env:." \
            --add-data "data:data"
      - run: |
          hdiutil create dist/MyTool.dmg \
            -volname "MyTool Installer" \
            -srcfolder dist/MyTool.app \
            -ov -format UDZO

      - name: Upload mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyTool-mac
          path: dist/MyTool.dmg
        id: upload

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: uv venv .venv
      - shell: pwsh
        run: |
          .\.venv\Scripts\Activate.ps1
          uv sync
          pyinstaller app.py `
            --name=MyTool `
            --windowed `
            --add-data "favo.png;." `
            --add-data ".env;." `
            --add-data "data;data"

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyTool-win
          path: dist/MyTool.exe

  release:
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows]

    steps:
      - name: Download mac artifact
        uses: actions/download-artifact@v4
        with:
          name: MyTool-mac
          path: release-assets

      - name: Download win artifact
        uses: actions/download-artifact@v4
        with:
          name: MyTool-win
          path: release-assets

      - name: Upload release files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-assets/MyTool.dmg
            release-assets/MyTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}