name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Build macOS .app with PyInstaller
        run: |
          pyinstaller app.py \
            --name=MyTool \
            --windowed \
            --icon=favo.icns \
            --add-data "favo.png:." \
            --add-data ".env:." \
            --add-data "data:data"

      - name: Create DMG from .app
        run: |
          hdiutil create dist/MyTool.dmg \
            -volname "MyTool Installer" \
            -srcfolder dist/MyTool.app \
            -ov -format UDZO

      - name: Upload .dmg to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MyTool.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Build Windows .exe with PyInstaller
        run: |
          pyinstaller app.py ^
            --name=MyTool ^
            --windowed ^
            --add-data "favo.png;." ^
            --add-data ".env;." ^
            --add-data "data;data"

      - name: Upload .exe to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/MyTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}